### PR TITLE
fix dashboard create from template error

### PR DESCRIPTION
**Pull request by jeanawhou**
Ticket link: https://app.ora.pm/p/613886e300e4495da43eb09e27f99a61?v=0&t=k&c=220a3ddc33f2495388c36c6fdc24dc87
added beats length check

### CODE REVIEW

**Comment by Quiescent** [comment]
@jeanawhou, were you able to replicate this?
It shouldn't be possible to replicate anymore.
I've replied on the ticket.

**Comment by jeanawhou** [comment]
@Quiescent checking...

**Comment by Quiescent** [comment]
> @Quiescent checking...

Did you ever find out? :)

**Comment by jeanawhou** [comment]
> > @Quiescent checking...
> 
> Did you ever find out? :)

Oh sorry i replied at Ora instead. My last reply was 10 days ago :'( 
image

I checked again just now and i still get the error on staging

**Comment by Quiescent** [comment]
Oh gosh!  I should've checked there too! XD

I can't replicate it, and when I fixed this, @cameronsutter confirmed that it worked for him.
Could you please try toggling the act structure beta on and off and then try again?

**Comment by jeanawhou** [comment]
> Oh gosh! I should've checked there too! XD
> 
> I can't replicate it, and when I fixed this, @cameronsutter confirmed that it worked for him.
> Could you please try toggling the act structure beta on and off and then try again?

It worked, we can close this pr now :)

**Pull request closed without merging**
