### PR TITLE
Edit duplicate delete btn

### PR DESCRIPTION
**Pull request by jeanawhou**
Ticket: https://airtable.com/appfbr7vlSqIfZ9Sn/tblAmQkxs32m46J4N/viwW0oDccShKAvbCd/rec8j9AMFqkTpjd4p?blocks=hide

Demo:

https://user-images.githubusercontent.com/19387007/180411388-8191d8f2-823e-462c-8353-0dd7fd436e48.mp4

### CODE REVIEW

**Review by Quiescent — CHANGES_REQUESTED** [review]
@jeanawhou, I think you've gotten the wrong idea here.
We want the controls to look like the line title cell controls.
i.e. use the `PlottrFloater` component to make them appear beneath each item.

**Comment by jeanawhou** [comment]
@cameronsutter @Quiescent updated. What do you think? 

https://user-images.githubusercontent.com/19387007/180772673-ee4af24e-e6de-4dae-a9af-4d97b775b6cb.mp4

**Comment by Quiescent** [comment]
@jeanawhou Looking better!
We need the controls for other items to appear when you hover over them, and I'd also like to test what it looks like when the controls hover on the right side (in a vertical button group).

**Comment by jeanawhou** [comment]
@Quiescent @cameronsutter updated 😅 what do you think?

**Comment by cameronsutter** [comment]
Love it!

**Comment by jeanawhou** [comment]
@cameronsutter @Quiescent  sorry i forgot the video demo for the hover and the button group when they're positioned on the right 😅 

https://user-images.githubusercontent.com/19387007/180909625-2e411de4-95d5-4216-987a-e43b3b3ded9a.mp4

**Comment by cameronsutter** [comment]
Oh haha. I rewatched your first video. I actually think I like that the best. Instead of hover below it, it's better-looking just hovering directly over the component like you have in the first video.

Sorry for the back and forth, but sometimes I don't know until I see it a few ways. Thanks for being patient!!

**Comment by Quiescent** [comment]
> Oh haha. I rewatched your first video. I actually think I like that the best. Instead of hover below it, it's better-looking just hovering directly over the component like you have in the first video.
> 
> Sorry for the back and forth, but sometimes I don't know until I see it a few ways. Thanks for being patient!!

@cameronsutter, in that first video, did you notice that it covers the name and category when they're long enough?
I still think that we should put the buttons into a vertical button group (i.e. `<ButtonGroup vertical` and use `placement="right"` on the `<Floater`).

**Comment by cameronsutter** [comment]
I did see that and i was surprised too that I'm ok with it. I think it's because it only covers it when it's hovering.

But you're right too. I do want to see it as a vertical button group on the right side. That might be the best way.

I know we have to merge this today. Is there enough time to change that? If so, let's make that change, merge it, and know that we might tweak it in the future

**Comment by Quiescent** [comment]
> I did see that and i was surprised too that I'm ok with it. I think it's because it only covers it when it's hovering.
> 
> But you're right too. I do want to see it as a vertical button group on the right side. That might be the best way.
> 
> I know we have to merge this today. Is there enough time to change that? If so, let's make that change, merge it, and know that we might tweak it in the future

It should be a matter of changing the two props I noted.  @jeanawhou, do you think you can get to it?

**Comment by jeanawhou** [comment]
@Quiescent @cameronsutter update demo 😅 

https://user-images.githubusercontent.com/19387007/181037898-488d86bd-97ef-4413-9610-a9a031561a9d.mp4

**Comment by Quiescent** [comment]
> @Quiescent @cameronsutter update demo 😅
> Screen.Recording.2022-07-26.at.10.46.36.PM.mp4

I think this looks way better! :)  WDYT, @cameronsutter ?

**Comment by cameronsutter** [comment]
Yup, that's the winner! 🥇 Looks great @jeanawhou. MERGE IT 🚀

**Review by Quiescent — APPROVED** [review]
Well done! :)

**Pull request merged**
