### PR TITLE
added background and border insert card icon

### PR DESCRIPTION
**Pull request by jeanawhou**
Ticket: https://airtable.com/appfbr7vlSqIfZ9Sn/tblP6AWIpvkOYZ0jR/viwou8K2UyUSkWGts/rec0uL7VjgmJqX7W2?blocks=hide

Demo

https://user-images.githubusercontent.com/19387007/173737235-05e50b75-1eec-452b-a9ac-56bcfd402603.mp4

### CODE REVIEW

**Comment by Quiescent** [comment]
I think you're looking at the wrong insert control.
Here's what I think the ticket is referring to and how we might fix it:
screenshot

Please revert the other change.  (Sorry!)

**Review by Quiescent — CHANGES_REQUESTED** [review]
See previous comment.

**Comment by jeanawhou** [comment]
@Quiescent pr updated wdyt ? 😅 

https://user-images.githubusercontent.com/19387007/173746302-874ff0ad-ee8e-4ead-b3dc-2d649439fcd2.mp4

**Review by Quiescent — APPROVED** [review]
It's better, and I think we'll probably end up merging it.
But I'd like @cameronsutter 's opinion on the button getting a background and border for the stacked vertical view only.
It's a little bit inconsistent.

**Comment by Quiescent** [comment]
Changed the base here too.

**Comment by cameronsutter** [comment]
@jeanawhou @Quiescent It's a little inconsistent, but given the circumstance it makes sense and I think it looks good. +2

**Pull request merged**
