### PR TITLE
Import scrivener failing files

### PR DESCRIPTION
**Pull request by jeanawhou**
ticket: https://airtable.com/appfbr7vlSqIfZ9Sn/tblAmQkxs32m46J4N/viwkbPCQaaQOxPRQQ/recoWiPcB3BXX6Ofm?blocks=hide

@Quiescent @cameronsutter most of the files are the individual files from the example scrivener you can check the commits to see the significant changes specifically the last one 😅 🙇

### CODE REVIEW

**Comment by Quiescent** [comment]
Looking great!
Only three comments:
 1. Please don't check in the generated file `test.pltr`.
 2. Please can you import those three files and test them individually.
 3. Please can you check that the content of the generated files matches what we expected (based on importing them today).

**Comment by jeanawhou** [comment]
@Quiescent @cameronsutter PR updated

**Comment by Quiescent** [comment]
@jeanawhou does this test importing all three files?  It looks like it only imports the one file:
`    "import-test": "electron --inspect=5858 . --import-from-scrivener ./examples/A-Coroners-Tale-Temp2.scriv --output-file ./examples/test_output/A-Coroners-Tale-Temp2.pltr && jest test/end-to-end/import-scrivener.test.js"`

**Comment by jeanawhou** [comment]
@Quiescent PR updated 😅

**Review by Quiescent — APPROVED** [review]
LGTM!  Good job sticking with this through all the changes! :raised_hands:

**Pull request merged**
