### PR TITLE
added darkmode text color

### PR DESCRIPTION
**Pull request by jeanawhou**
ticket link: https://app.ora.pm/p/613886e300e4495da43eb09e27f99a61?v=0&t=k&c=bf95b1673788479385e7234b4b58e813

disabled-navpill-dark
disabled-nav-pill-light
Nav-pill on dark and light theme

Screenshot from 2021-04-17 09-31-36
Screenshot from 2021-04-17 09-31-02
Line title cell on light and dark theme

### CODE REVIEW

**Review by murfdog64 — COMMENTED** [review]
Looks good to me ✅

**Comment by jeanawhou** [comment]
I will just include another darkmode fix in the same branch. Let me know what you think with this one as well.
verifyview-light
verifyview-dark

**Review by Quiescent — APPROVED** [review]
Looks good.  LGTM!

**Comment by Quiescent** [comment]
> I will just include another darkmode fix in the same branch. Let me know what you think with this one as well.
> verifyview-light
> verifyview-dark

We might want a follow up for the blue of the cancel there.
It's very hard to read against grey.

I think that we can go ahead with merging this PR though, because it fixes some really important problems elsewhere.

**Comment by jeanawhou** [comment]
@Quiescent  I was thinking the same im not just sure with blue variant to choose

**Pull request merged**
